"""
Gravity Module: Optical Metric and Impedance Gradients
======================================================
Gravity is modeled as the macroscopic optical refraction of the LC vacuum
network. A massive topological defect polarizes the local inductance and
permittivity, creating a refractive index gradient that bends all wave
propagation (photons and massive wave-packets alike).

Key results (Ch. 9):
  - Principal radial strain:  ε₁₁(r) = 7GM/(c²r)
  - Refractive index:         n(r) = 1 + 2GM/(c²r)
  - Achromatic matching:      μ'/ε' scales symmetrically → Z₀ invariant
"""

from ave.axioms.scale_invariant import impedance as _impedance
from ave.axioms.scale_invariant import saturation_factor
from ave.core.constants import C_0, EPSILON_0, MU_0, G


def principal_radial_strain(mass_kg: float, radius_m: float) -> float:
    """
    1D principal radial strain generated by a point mass via Laplace eqn.

    ε₁₁(r) = 7GM / (c²r)

    The factor 7 emerges from the isotropic Machian stress boundary
    T_max,g = c⁴/(7G).

    Args:
        mass_kg: Source mass [kg].
        radius_m: Distance from center of mass [m]. Must be > 0.

    Returns:
        Dimensionless radial strain.
    """
    if radius_m <= 0:
        raise ValueError("Radius must be > 0.")
    return (7.0 * G * mass_kg) / (C_0**2 * radius_m)


def refractive_index(mass_kg: float, radius_m: float) -> float:
    """
    Effective scalar refractive index of the vacuum at distance r from mass M.

    n(r) = 1 + (ν_vac) · ε₁₁(r) = 1 + 2GM/(c²r)

    where ν_vac = 2/7 is the trace-reversed Poisson ratio.

    Args:
        mass_kg: Source mass [kg].
        radius_m: Distance from center of mass [m].

    Returns:
        Scalar refractive index (≥ 1.0 always for positive mass).
    """
    from ave.core.constants import NU_VAC
    from ave.core.universal_operators import universal_refractive_index

    eps = principal_radial_strain(mass_kg, radius_m)
    return universal_refractive_index(eps, nu_vac=NU_VAC)


def is_dielectric_rupture(mass_kg: float, radius_m: float) -> bool:
    """
    Checks if local metric strain exceeds the Axiom 4 dielectric saturation
    limit (unitary strain). This defines the Event Horizon.

    Rupture when: 2GM/(c²r) ≥ 1    →   r ≤ 2GM/c² (Schwarzschild radius)

    Args:
        mass_kg: Source mass [kg].
        radius_m: Distance from center of mass [m].

    Returns:
        True if within the event horizon (dielectric rupture).
    """
    schwarzschild_r = (2.0 * G * mass_kg) / C_0**2
    return radius_m <= schwarzschild_r


def schwarzschild_radius(mass_kg: float) -> float:
    """
    The Schwarzschild radius as the dielectric rupture limit.

    R_s = 2GM/c²

    Args:
        mass_kg: Source mass [kg].

    Returns:
        Schwarzschild radius [m].
    """
    return (2.0 * G * mass_kg) / C_0**2


def local_mu(mass_kg: float, radius_m: float) -> float:
    """
    Achromatic impedance matching: local permeability scales with n(r).

    μ'(r) = n(r) · μ₀

    Args:
        mass_kg: Source mass [kg].
        radius_m: Distance [m].

    Returns:
        Local permeability [H/m].
    """
    n = refractive_index(mass_kg, radius_m)
    return n * MU_0


def local_epsilon(mass_kg: float, radius_m: float) -> float:
    """
    Achromatic impedance matching: local permittivity scales with n(r).

    ε'(r) = n(r) · ε₀

    Args:
        mass_kg: Source mass [kg].
        radius_m: Distance [m].

    Returns:
        Local permittivity [F/m].
    """
    n = refractive_index(mass_kg, radius_m)
    return n * EPSILON_0


def local_impedance(mass_kg: float, radius_m: float) -> float:
    """
    Local transverse impedance — INVARIANT under gravitational strain.

    Z'(r) = √(μ'/ε') = √(n·μ₀ / n·ε₀) = Z₀

    This achromatic matching guarantees no reflection at gravitational
    impedance boundaries (gravity acts as a perfect lens).

    Args:
        mass_kg: Source mass [kg].
        radius_m: Distance [m].

    Returns:
        Local impedance [Ω] — should always equal Z₀.
    """
    mu = local_mu(mass_kg, radius_m)
    ep = local_epsilon(mass_kg, radius_m)
    return _impedance(mu, ep)


def gravitational_potential(mass_kg: float, radius_m: float) -> float:
    """
    Newtonian gravitational potential as ponderomotive wave energy.

    U(r) = -GM/r

    Derived from F = -∇(m c²/n(r)) in the wave-packet limit.

    Args:
        mass_kg: Source mass [kg].
        radius_m: Distance [m].

    Returns:
        Gravitational potential [J/kg].
    """
    if radius_m <= 0:
        raise ValueError("Radius must be > 0.")
    return -G * mass_kg / radius_m


def einstein_deflection_angle(mass_kg: float, impact_parameter_m: float) -> float:
    """
    Photon deflection via the optical metric (Snell's law through n(r)).

    δ = 4GM / (bc²)

    This matches GR exactly and is DOUBLE the Newtonian corpuscular prediction.

    Args:
        mass_kg: Source mass [kg].
        impact_parameter_m: Closest approach distance [m].

    Returns:
        Deflection angle [radians].
    """
    if impact_parameter_m <= 0:
        raise ValueError("Impact parameter must be > 0.")
    return (4.0 * G * mass_kg) / (impact_parameter_m * C_0**2)


# ═══════════════════════════════════════════════════════════════════
# Lattice Phase Transition at Saturation Boundary
# ═══════════════════════════════════════════════════════════════════
#
# SYMMETRIC GRAVITY:  Z(r) = √(μ'/ε') = Z₀  *everywhere*.
# Both μ' and ε' scale as n(r), so Z is invariant.  There is NO
# impedance mismatch and Γ = 0 for transverse waves at all radii.
#
# BH confinement arises from a LATTICE PHASE TRANSITION at ε₁₁ = 1:
#   - Shear modulus G_shear → 0 (topology melts)
#   - Group velocity c_g → 0 (energy freezes)
#   - GWs (transverse shear waves) CANNOT propagate in the ruptured
#     interior (same as transverse acoustic waves in a fluid)
#   - The interior is a PERFECT REFLECTOR for shear perturbations
#
# For PARTICLES, confinement uses a different mechanism:
#   - μ saturates first at torus knot self-intersections
#   - Z → 0, Γ → −1 (short circuit, standing wave = rest mass)
# ═══════════════════════════════════════════════════════════════════


def saturation_radius(mass_kg: float) -> float:
    """
    The Axiom 4 saturation boundary: radius where ε₁₁(r) = 1.

    r_sat = 7·G·M/c² = 7·M_g = 3.5·r_s

    This is the elastic limit of the lattice — the phase transition
    boundary between the solid (shear-supporting) lattice and the
    ruptured (topology-melted) interior.

    Args:
        mass_kg: Source mass [kg].

    Returns:
        Saturation radius [m].
    """
    return (7.0 * G * mass_kg) / C_0**2


def gravitational_saturation_factor(mass_kg: float, radius_m: float) -> float:
    """
    Axiom 4 saturation factor for gravitational strain.

    The principal radial strain ε₁₁(r) = 7GM/(c²r) is the amplitude
    parameter A. The yield limit A_yield = 1 (unitary strain).

        S_grav(r) = √(1 - ε₁₁²)

    At flat space: S = 1 (no strain).
    At r = R_s:    ε₁₁ = 7/2 > 1, so S = 0 (full saturation / rupture).
    Onset at r ≈ 3.5 R_s where ε₁₁ = 1.

    Args:
        mass_kg: Source mass [kg].
        radius_m: Distance from center of mass [m].

    Returns:
        Saturation factor in [0, 1]. Returns 0 if inside the
        saturation shell (ε₁₁ ≥ 1).
    """
    strain = principal_radial_strain(mass_kg, radius_m)
    return float(saturation_factor(strain, yield_limit=1.0, clip=True))


def shear_modulus_factor(mass_kg: float, radius_m: float) -> float:
    """
    Shear modulus relative to the vacuum baseline.

    G_shear(r) / G_shear(∞) = S(r) = √(1 − ε₁₁²)

    At r > r_sat: G_shear > 0 (elastic lattice, GWs propagate)
    At r = r_sat: G_shear = 0 (phase transition)
    At r < r_sat: G_shear = 0 (ruptured, topology melted)

    This is identical to gravitational_saturation_factor but named
    for physical clarity: gravitational waves are shear waves, and
    this factor determines whether they can propagate.

    Args:
        mass_kg: Source mass [kg].
        radius_m: Distance from center of mass [m].

    Returns:
        Shear modulus ratio in [0, 1].
    """
    return gravitational_saturation_factor(mass_kg, radius_m)
