"""
AVE SPICE Netlist Compiler
==========================

Translates AVE solver outputs (L, C, R, coupling) into cascaded
AVE_VACUUM_CELL netlist (.cir) files for ngspice verification.

This compiler is the bridge between the Python physics engine and
the industry-standard SPICE verification path:

    Python solver → compile_* → .cir → ngspice → validation

All generated netlists reference the canonical AVE_VACUUM_CELL
subcircuit from ave_vacuum_cell.lib.

Tier 3 Solver (consumes Tiers 1+2, never re-derives operators).

Reference: Backmatter App 6 — SPICE Verification Manual
"""

import os
import textwrap
from pathlib import Path

# Location of the canonical .lib file
_LIB_DIR = Path(__file__).resolve().parent.parent / "hardware" / "spice_models"
_LIB_FILE = _LIB_DIR / "ave_vacuum_cell.lib"


def _lib_include_path() -> str:
    """Return the .INCLUDE directive for the universal cell library."""
    return f'.INCLUDE {_LIB_FILE}'


def compile_ee_bench_dc_sweep(
    c0: float = 10e-12,
    v_yield: float = 43653.7,
    v_max: float = 45000.0,
    v_step: float = 100.0,
    title: str = "EE Bench Dielectric Yield Plateau — AVE DC Sweep",
) -> str:
    """
    Generate an ngspice netlist for the EE Bench capacitance plateau test.

    This is the simplest possible verification: a single vacuum cell
    driven through a DC sweep from 0 to V_max.  The measured charge
    Q(V) should follow Q = C0 × V / sqrt(1 - (V/V_yield)^2).

    Plotting dQ/dV vs. V reveals the Axiom 4 capacitance plateau.

    Parameters
    ----------
    c0 : float
        Base capacitance in farads (default: 10 pF).
    v_yield : float
        Dielectric yield voltage in volts (default: V_YIELD from constants.py).
    v_max : float
        Maximum sweep voltage in volts.
    v_step : float
        Voltage step size in volts.
    title : str
        Netlist title line.

    Returns
    -------
    str
        Complete ngspice-compatible .cir netlist.
    """
    return textwrap.dedent(f"""\
        * {title}
        * Generated by ave.solvers.spice_netlist_compiler
        *
        {_lib_include_path()}

        * DC sweep source
        V_SWEEP N_GAP GND DC 0

        * Universal vacuum cell (varactor only)
        X1 N_GAP GND AVE_EE_BENCH C0={c0:.6e} V_YLD={v_yield:.1f}

        * Parasitic shunt for DC convergence
        R_PAR N_GAP GND 1G

        .DC V_SWEEP 0 {v_max:.0f} {v_step:.0f}

        .control
        run
        * Plot C_eff / C0 = d(charge)/dV / C0
        plot deriv(i(V_SWEEP)) / {c0:.6e} title 'C_eff/C0 vs V'
        .endc

        .END
    """)


def compile_lcr_network(
    nodes: list[dict],
    edges: list[dict],
    title: str = "AVE LCR Network",
    analysis: str = "ac",
    f_start: float = 1e9,
    f_stop: float = 1e15,
    n_points: int = 1000,
    v_yield: float = 43653.7,
    i_max: float = 124.4,
    use_nonlinear: bool = True,
) -> str:
    """
    Compile a generic LCR network to an ngspice netlist.

    Each node becomes a circuit node; each edge instantiates either
    an AVE_VACUUM_CELL (nonlinear) or AVE_VACUUM_CELL_LINEAR (linear)
    subcircuit with the specified L, C, R parameters.

    Parameters
    ----------
    nodes : list[dict]
        Node definitions.  Each dict has:
            'id': str (node name, e.g. 'N1')
            'shunt_r': float (optional shunt resistance to ground)
    edges : list[dict]
        Edge definitions.  Each dict has:
            'from': str (source node id)
            'to': str (destination node id)
            'L': float (inductance in H)
            'C': float (capacitance in F)
            'R': float (resistance in Ohm, default 0)
    title : str
        Netlist title.
    analysis : str
        'ac' for AC sweep, 'tran' for transient.
    f_start, f_stop : float
        Frequency range for AC analysis.
    n_points : int
        Number of frequency points (decade sweep).
    v_yield, i_max : float
        Saturation thresholds (default: constants.py values).
    use_nonlinear : bool
        If True, use AVE_VACUUM_CELL; if False, use LINEAR variant.

    Returns
    -------
    str
        Complete ngspice .cir netlist.
    """
    cell_type = "AVE_VACUUM_CELL" if use_nonlinear else "AVE_VACUUM_CELL_LINEAR"

    lines = [
        f"* {title}",
        "* Generated by ave.solvers.spice_netlist_compiler",
        "*",
        _lib_include_path(),
        "",
        "* AC excitation source (1V amplitude)",
        "V_SRC N_IN GND AC 1",
        "",
        "* ── Network topology ──",
    ]

    for i, edge in enumerate(edges):
        n_from = edge["from"]
        n_to = edge["to"]
        L = edge["L"]
        C = edge["C"]
        R = edge.get("R", 0.0)

        if use_nonlinear:
            lines.append(
                f"X{i} {n_from} {n_to} {cell_type}"
                f" L0={L:.6e} C0={C:.6e} R0={R:.6e}"
                f" V_YLD={v_yield:.1f} I_YMAX={i_max:.1f}"
            )
        else:
            lines.append(
                f"X{i} {n_from} {n_to} {cell_type}"
                f" L0={L:.6e} C0={C:.6e} R0={R:.6e}"
            )

    # Add shunt resistors
    lines.append("")
    lines.append("* ── Shunt loads ──")
    for node in nodes:
        shunt = node.get("shunt_r")
        if shunt and shunt < 1e15:
            lines.append(f"R_SH_{node['id']} {node['id']} GND {shunt:.6e}")

    # Termination
    lines.append(f"R_TERM {nodes[-1]['id']} GND 50")

    # Analysis
    lines.append("")
    if analysis == "ac":
        lines.append(
            f".AC DEC {n_points} {f_start:.6e} {f_stop:.6e}"
        )
        lines.append("")
        lines.append(".control")
        lines.append("run")
        lines.append(f"plot db(V({nodes[-1]['id']})) title 'Transfer Function (dB)'")
        lines.append(".endc")
    elif analysis == "tran":
        t_stop = 10.0 / f_start  # 10 cycles at lowest frequency
        t_step = 1.0 / f_stop / 10  # 10 steps per highest-freq cycle
        lines.append(f".TRAN {t_step:.6e} {t_stop:.6e}")

    lines.append("")
    lines.append(".END")

    return "\n".join(lines)


def compile_amino_acid_network(
    molecule_name: str,
    bonds: list[dict],
    title: str | None = None,
    v_yield: float = 43653.7,
) -> str:
    """
    Compile an amino acid's molecular topology to an ngspice netlist.

    Uses the organic mapper's absolute L/C values (from xi_topo
    transduction) to create a cascaded transmission line model.

    Parameters
    ----------
    molecule_name : str
        Molecule identifier (e.g. 'glycine', 'alanine').
    bonds : list[dict]
        Bond definitions.  Each dict has:
            'from': str (atom name, e.g. 'N1')
            'to': str (atom name, e.g. 'CA1')
            'L': float (inductance from mass mapping)
            'C': float (capacitance from compliance mapping)
            'R': float (damping, default 0)
    title : str or None
        Netlist title (auto-generated if None).
    v_yield : float
        Dielectric yield voltage.

    Returns
    -------
    str
        Complete ngspice .cir netlist with AC sweep.
    """
    if title is None:
        title = f"AVE Amino Acid SPICE Model: {molecule_name}"

    nodes_seen = set()
    node_list = []
    for bond in bonds:
        for key in ("from", "to"):
            if bond[key] not in nodes_seen:
                nodes_seen.add(bond[key])
                node_list.append({"id": bond[key]})

    return compile_lcr_network(
        nodes=node_list,
        edges=bonds,
        title=title,
        analysis="ac",
        f_start=1e12,   # 1 THz
        f_stop=100e12,   # 100 THz (covers FTIR range)
        n_points=500,
        v_yield=v_yield,
        use_nonlinear=True,
    )


def write_netlist(netlist: str, filepath: str | Path) -> Path:
    """
    Write a compiled netlist to a .cir file.

    Parameters
    ----------
    netlist : str
        The netlist string from a compile_* function.
    filepath : str or Path
        Output file path.

    Returns
    -------
    Path
        Absolute path to the written file.
    """
    filepath = Path(filepath)
    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text(netlist, encoding="utf-8")
    return filepath.resolve()


def lib_path() -> Path:
    """Return the absolute path to ave_vacuum_cell.lib."""
    return _LIB_FILE
