"""
Foundation Audit Test 3b: Drive-Amplitude Scan at ω=1.5 and ω=2.96.

Addresses Flag 1 from auditor 2026-04-30 (per
.agents/handoffs/L3_HANDOFF_2026-04-30.md §3.1 + doc 96 §11.3 v2):
distinguish "fundamental + 2nd harmonic" vs "two independent reactive
resonances at frequency ratio ≈ 2."

== Pre-registered hypotheses (frozen 2026-04-30) ==

H1 (INDEPENDENT MODES): The substrate has two distinct reactive
    eigenmodes at ω≈1.5·ω_C and ω≈2.96·ω_C. Each scales linearly with
    its own driver. Cross-coupling between drives is small (<<linear).

H2 (FUNDAMENTAL + 2ND HARMONIC): The 2.96·ω_C peak is the 2nd harmonic
    of the 1.5·ω_C fundamental, generated by intrinsic substrate
    nonlinearity (Op14 saturation kernel). Drive at ω=1.5 produces an
    A²-scaling response near 2ω=3.0; the observed 2.96 vs 3.00 gap is
    nonlinear frequency pull.

== Discriminator (single test) ==

Drive at ω=1.5 with amplitude A varying over 2.5 orders of magnitude
(A ∈ {1e-4, 3e-4, 1e-3, 3e-3, 1e-2, 3e-2}). For each A, measure
steady-state FFT power at three frequency bins:

  - f₁ = 1.50 (fundamental response) — predicted ∝ A in either H1 or H2
  - f₂ = 3.00 (2× drive frequency, harmonic location)
  - f₃ = 2.96 (observed second-peak location from T3)

Log-log slope of FFT(f₂) vs A:
  - slope ≈ 1 → linear (no harmonic generation) → favors H1
  - slope ≈ 2 → quadratic (true 2nd harmonic) → favors H2

If H2 is correct, FFT(f₂) > FFT(f₃) at all A (since 2nd harmonic
locks to 2ω_drive=3.0, not the substrate's 2.96 mode), unless
nonlinear pull at high A shifts harmonic location toward 2.96.

If H1 is correct, FFT(f₂) ≈ noise floor for all A (drive at 1.5
doesn't excite an independent mode at 3.0), and FFT(f₃) is also
noise-floor (1.5 driver doesn't excite the 2.96 mode).

== Cross-check at ω=2.96 ==

Symmetric scan at ω=2.96 (same A grid). FFT bins:
  - f₁ = 2.96 (fundamental response)
  - f₂ = 5.92 (2× drive, harmonic location)
  - f₃ = 1.50 (other-mode location — should be noise floor)

Drive at 2.96 is independent of whether 2.96 is a harmonic or a
mode (driving directly excites the resonance either way), so this
scan tests symmetry. Expected: FFT(f₃=1.5) ≈ noise floor in both H1
and H2 cases.

== PASS criteria ==

INDEPENDENT MODES (H1) declared if BOTH:
  (a) log-log slope of FFT(f=3.0) vs A at drive ω=1.5 is < 1.5 across
      the linear-amplitude range (A ≤ 0.003; below saturation onset
      A² ≈ √(2α) = 0.117), AND
  (b) FFT(f=3.0) at A=1e-4 is within 1 order of magnitude of FFT(f=4.5)
      and FFT(f=2.5) baseline noise — i.e., not a sharp peak.

2ND HARMONIC (H2) declared if BOTH:
  (a) log-log slope of FFT(f=3.0) vs A in [1.7, 2.3] across the
      linear-amplitude range, AND
  (b) FFT(f=3.0) at A=3e-3 exceeds noise floor by >> 10×.

INCONCLUSIVE if anything between.

== Latency check (per A39 v2 dual-criterion discipline) ==

This is NOT a bound-state-existence question; it's a mode-relation
classification at an established CW response peak. A39 v2's
frequency+localization dual-criterion doesn't directly apply.
Discriminator is FFT-power-vs-amplitude scaling exponent, which is
the correct empirical handle for nonlinear-vs-linear distinction.

Per Rule 10 PML-cell-exclusion: this driver tracks V_inc[center,
port=0] which is at lattice center (PML-excluded by construction at
N=16, PML=4 → active region 4..11).

== Compute estimate ==

12 runs × 50P × ~14s ≈ 3 minutes total.
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "src"))

from ave.topological.vacuum_engine import VacuumEngine3D


def run_cw_drive(omega_drive, drive_amplitude, n_periods=50, N=16, PML=4):
    """Drive at frequency omega_drive (in ω_C units) with given amplitude.

    Returns time trace v_traj of V_inc at center port 0.
    """
    DT = 1.0 / np.sqrt(2.0)
    COMPTON_PERIOD = 2.0 * np.pi
    N_STEPS = int(n_periods * COMPTON_PERIOD / DT)

    engine = VacuumEngine3D.from_args(
        N=N, pml=PML, temperature=0.0,
        amplitude_convention="V_SNAP",
        disable_cosserat_lc_force=True,
        enable_cosserat_self_terms=False,
    )

    center = (N // 2, N // 2, N // 2)
    v_traj = np.zeros(N_STEPS)

    for i in range(N_STEPS):
        t = i * DT
        drive_value = drive_amplitude * np.cos(omega_drive * t)
        for p in range(4):
            engine.k4.V_inc[center[0], center[1], center[2], p] += drive_value
        engine.step()
        v_traj[i] = engine.k4.V_inc[center[0], center[1], center[2], 0]

    return v_traj, DT, N_STEPS


def fft_power_at(v_traj, dt, target_freqs, transient_periods=25):
    """FFT power spectrum at target frequencies (in rad/time units).

    Excludes first `transient_periods` Compton periods to remove transient.
    Returns dict {freq: amplitude_at_that_freq}.
    """
    COMPTON_PERIOD = 2.0 * np.pi
    sw_start = int(transient_periods * COMPTON_PERIOD / dt)
    if sw_start >= len(v_traj):
        return {f: 0.0 for f in target_freqs}, 0.0

    v_steady = v_traj[sw_start:]
    n = len(v_steady)
    fft_vals = np.fft.rfft(v_steady)
    freqs = np.fft.rfftfreq(n, d=dt) * 2.0 * np.pi  # angular frequency

    # FFT amplitude (peak-equivalent): scale by 2/N for one-sided
    fft_amp = 2.0 * np.abs(fft_vals) / n

    out = {}
    for f_target in target_freqs:
        # Find nearest frequency bin
        idx = int(np.argmin(np.abs(freqs - f_target)))
        out[float(f_target)] = float(fft_amp[idx])

    # Noise floor estimate: median FFT amplitude over full spectrum
    noise_floor = float(np.median(fft_amp))
    return out, noise_floor


def lockin(v_traj, dt, omega_drive, transient_periods=25):
    """Lock-in amplitude at drive frequency (matches T3 driver method)."""
    COMPTON_PERIOD = 2.0 * np.pi
    sw_start = int(transient_periods * COMPTON_PERIOD / dt)
    if sw_start >= len(v_traj):
        return 0.0
    v_steady = v_traj[sw_start:]
    t_steady = np.arange(len(v_steady)) * dt + sw_start * dt
    cos_drive = np.cos(omega_drive * t_steady)
    sin_drive = np.sin(omega_drive * t_steady)
    I = 2.0 * float(np.mean(v_steady * cos_drive))
    Q = 2.0 * float(np.mean(v_steady * sin_drive))
    return float(np.sqrt(I**2 + Q**2))


def main():
    print("=" * 78, flush=True)
    print("  Foundation Audit Test 3b: Drive-Amplitude Scan")
    print("  Pre-registered: distinguish independent modes (H1) vs")
    print("  fundamental+2nd-harmonic (H2) at substrate peaks ω=1.5 + 2.96")
    print("=" * 78, flush=True)

    # Drive amplitude sweep: 2.5 orders of magnitude
    amplitudes = [1e-4, 3e-4, 1e-3, 3e-3, 1e-2, 3e-2]
    drive_freqs = [1.5, 2.96]

    # FFT bins to track per drive frequency
    fft_targets = {
        1.5: [1.50, 3.00, 2.96, 4.50, 2.50],   # f₁=drive, f₂=2*drive, f₃=other peak,
                                                # last two for noise-baseline ref
        2.96: [2.96, 5.92, 1.50, 4.50, 3.50],  # f₁=drive, f₂=2*drive, f₃=other peak,
                                                # last two for noise-baseline ref
    }

    results = []
    t_start = time.time()

    for omega_drive in drive_freqs:
        print(f"\n  Drive frequency ω = {omega_drive:.3f}·ω_C")
        print(f"  {'A':>10} {'lockin@drive':>14} {'FFT@'+str(fft_targets[omega_drive][0]):>11}"
              f"  {'FFT@'+str(fft_targets[omega_drive][1]):>11}  {'FFT@'+str(fft_targets[omega_drive][2]):>11}"
              f"  {'noise':>10}  {'A²':>9}")

        for A in amplitudes:
            t0 = time.time()
            v_traj, dt, n_steps = run_cw_drive(omega_drive, A)
            elapsed = time.time() - t0

            lock_amp = lockin(v_traj, dt, omega_drive)
            fft_at, noise = fft_power_at(v_traj, dt, fft_targets[omega_drive])

            # A² for saturation-onset check (A²_yield ≈ √(2α) = 0.117 in V_SNAP units)
            A_sq = A * A

            row = {
                "omega_drive": omega_drive,
                "drive_amplitude": A,
                "drive_amplitude_squared": A_sq,
                "lockin_at_drive": lock_amp,
                "fft_targets": fft_targets[omega_drive],
                "fft_at": fft_at,
                "fft_noise_floor": noise,
                "n_steps": n_steps,
                "elapsed_s": elapsed,
            }
            results.append(row)

            f_targets = fft_targets[omega_drive]
            print(f"  {A:>10.1e} {lock_amp:>14.4e} {fft_at[f_targets[0]]:>11.4e}"
                  f"  {fft_at[f_targets[1]]:>11.4e}  {fft_at[f_targets[2]]:>11.4e}"
                  f"  {noise:>10.3e}  {A_sq:>9.2e}  ({elapsed:.1f}s)")

    total_elapsed = time.time() - t_start
    print(f"\n  Total elapsed: {total_elapsed:.1f}s")

    # Adjudicate H1 vs H2 from drive=1.5 scan
    print()
    print("=" * 78)
    print("  ADJUDICATION (per pre-registered criteria)")
    print("=" * 78)

    drive15 = [r for r in results if r["omega_drive"] == 1.5]
    A_arr = np.array([r["drive_amplitude"] for r in drive15])
    fft_at_1p5 = np.array([r["fft_at"][1.50] for r in drive15])
    fft_at_3p0 = np.array([r["fft_at"][3.00] for r in drive15])
    fft_at_2p96 = np.array([r["fft_at"][2.96] for r in drive15])
    noise = np.array([r["fft_noise_floor"] for r in drive15])

    # Log-log slope of FFT@3.0 vs A across linear range (A ≤ 3e-3 below saturation)
    linear_mask = A_arr <= 3e-3
    if np.sum(linear_mask) >= 2:
        log_A = np.log10(A_arr[linear_mask])
        log_fft_1p5 = np.log10(np.maximum(fft_at_1p5[linear_mask], 1e-20))
        log_fft_3p0 = np.log10(np.maximum(fft_at_3p0[linear_mask], 1e-20))
        log_fft_2p96 = np.log10(np.maximum(fft_at_2p96[linear_mask], 1e-20))

        slope_at_drive = float(np.polyfit(log_A, log_fft_1p5, 1)[0])
        slope_at_2drive = float(np.polyfit(log_A, log_fft_3p0, 1)[0])
        slope_at_2p96 = float(np.polyfit(log_A, log_fft_2p96, 1)[0])

        print(f"\n  Drive ω=1.5, log-log slopes (A ≤ 3e-3, linear regime):")
        print(f"    FFT @ f=1.50 (fundamental):  slope = {slope_at_drive:+.3f}  (predicted ≈ 1)")
        print(f"    FFT @ f=3.00 (2× drive):     slope = {slope_at_2drive:+.3f}  (H1: <1.5; H2: ≈2)")
        print(f"    FFT @ f=2.96 (other peak):   slope = {slope_at_2p96:+.3f}  (H1+H2 both: ≈ 0; noise floor)")

        # Headroom over noise floor at A=3e-3 (mid-range, before saturation)
        idx_3e3 = int(np.argmin(np.abs(A_arr - 3e-3)))
        ratio_3p0_over_noise = fft_at_3p0[idx_3e3] / max(noise[idx_3e3], 1e-20)
        ratio_2p96_over_noise = fft_at_2p96[idx_3e3] / max(noise[idx_3e3], 1e-20)
        print(f"\n  At A=3e-3 (linear regime):")
        print(f"    FFT(f=3.0) / noise_floor = {ratio_3p0_over_noise:.2f}")
        print(f"    FFT(f=2.96) / noise_floor = {ratio_2p96_over_noise:.2f}")

        # Verdict
        h2_slope_pass = 1.7 <= slope_at_2drive <= 2.3
        h2_amp_pass = ratio_3p0_over_noise > 10.0
        h1_slope_pass = slope_at_2drive < 1.5
        h1_amp_pass = ratio_3p0_over_noise < 10.0

        print(f"\n  Verdict:")
        if h2_slope_pass and h2_amp_pass:
            print(f"    → H2 (fundamental + 2nd harmonic): PASS")
        elif h1_slope_pass and h1_amp_pass:
            print(f"    → H1 (independent modes): PASS")
        else:
            print(f"    → INCONCLUSIVE")
            print(f"      slope_at_2drive = {slope_at_2drive:+.3f} "
                  f"(H1 needs <1.5, H2 needs [1.7, 2.3])")
            print(f"      amp_ratio = {ratio_3p0_over_noise:.2f} "
                  f"(H1 needs <10×, H2 needs >10×)")

        verdict = {
            "slope_at_drive_1p5": slope_at_drive,
            "slope_at_3p0": slope_at_2drive,
            "slope_at_2p96": slope_at_2p96,
            "fft_at_3p0_over_noise_at_A3em3": ratio_3p0_over_noise,
            "fft_at_2p96_over_noise_at_A3em3": ratio_2p96_over_noise,
            "h1_independent_modes_pass": bool(h1_slope_pass and h1_amp_pass),
            "h2_2nd_harmonic_pass": bool(h2_slope_pass and h2_amp_pass),
        }
    else:
        verdict = {"error": "insufficient linear-regime points"}

    out = {
        "test": "Foundation Audit Test 3b: Drive-Amplitude Scan",
        "addresses_flag": "Flag 1 from auditor 2026-04-30 (mode-relation overclaim)",
        "amplitudes": amplitudes,
        "drive_frequencies": drive_freqs,
        "results": results,
        "verdict": verdict,
        "elapsed_total_s": total_elapsed,
    }
    out_path = Path(__file__).parent / "r10_v8_foundation_audit_t3b_amplitude_scan_results.json"
    out_path.write_text(json.dumps(out, indent=2, default=str))
    print(f"\nSaved {out_path.relative_to(Path.cwd())}")


if __name__ == "__main__":
    main()
