"""Import + output-path bootstrap for the vol_6 animation drivers.

WHY THIS EXISTS (2026-08-23 provenance-hole repair, Grant ruling option (b))
----------------------------------------------------------------------------
The 13 ``animate_*.py`` drivers in this directory imported

    from periodic_table.simulations.simulate_element import get_nucleon_coordinates

and no ``periodic_table`` package exists (``importlib.util.find_spec`` returns
``None``). The import target moved paths at the IP partition; the module that
survived is IN-TREE at
``src/scripts/vol_6_periodic_table/simulations/simulate_element.py`` and still
carries ``def get_nucleon_coordinates``.

Two facts constrain how the drivers may reach it:

1. ``simulate_element`` uses a PACKAGE-RELATIVE import
   (``from .spice_exporter import generate_spice_netlist``,
   ``simulate_element.py:45``), so it CANNOT be loaded by putting
   ``simulations/`` on ``sys.path`` and doing ``import simulate_element`` —
   that raises ``ImportError: attempted relative import with no known parent
   package`` (probe-verified 2026-08-23). It must be imported as a package
   member.
2. The directory is ``vol_6_periodic_table/`` on disk but the documented import
   alias is ``periodic_table`` (``src/scripts/AGENTS.md`` §"The
   ``periodic_table`` import namespace").

So this module registers ``vol_6_periodic_table/`` under the ``periodic_table``
name as a namespace package. That is the same bootstrap already proven in-tree
at ``src/scripts/vol_6_periodic_table/simulations/regenerate_all_figures.py``
(lines 36-50); it is factored here so the 13 drivers carry one shared,
gate-checkable copy instead of thirteen.

Everything is anchored on ``__file__``, never on the process cwd, so a driver
runs correctly from any directory and from any git worktree.

OUTPUT POLICY
-------------
The drivers previously wrote GIFs to the relative paths ``"../figures"`` and
``"periodic_table/figures"`` — the first is cwd-dependent and the second does
not exist. Both are replaced by ``output_path()``, which resolves into the
gitignored driver-scratch dir ``animations/_output/`` (matched by the
``src/scripts/**/_output/`` rule; 2026-07-03 figure-hygiene policy D4).

This is correct because the manuscript embeds NO animations. The cited vol_6
artefact is the still frame ``<element>_dynamic_flux.png``, and every one of
those is regenerated by ``simulations/regenerate_all_figures.py``, whose
generic loop at :197 writes ``f"{name}_dynamic_flux.png"`` for all 20 tabulated
elements into ``manuscript/vol_6_periodic_table/figures/``. The GIFs are
exploratory scratch, so they must not land in a tracked ``figures/`` dir.

PROVENANCE CAVEAT
-----------------
Repairing these drivers restores METHOD provenance, not byte identity: per the
``figure-bit-reproducibility`` open item, regeneration is deterministic but not
bit-exact across matplotlib versions, so LOOKUP (git history) remains the
identity-bearing path for the printed figures.
"""

from __future__ import annotations

import os
import pathlib
import sys
import types

# ``animations/`` -> ``vol_6_periodic_table/`` -> ``scripts/`` -> ``src/``
_ANIM_DIR = pathlib.Path(__file__).resolve().parent
_PT_DIR = _ANIM_DIR.parent
_SRC_DIR = _PT_DIR.parent.parent

# This worktree's ``src/`` must win over the editable-install .pth (which pins
# ``ave`` to the MAIN checkout's src/). See CLAUDE.md "Worktree-aware local
# validation".
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))

if "periodic_table" not in sys.modules:
    _pt = types.ModuleType("periodic_table")
    _pt.__path__ = [str(_PT_DIR)]  # namespace package: the dir has no __init__.py
    sys.modules["periodic_table"] = _pt

from periodic_table.simulations.simulate_element import get_nucleon_coordinates  # noqa: E402

#: Gitignored driver-scratch dir for animation output (policy note above).
OUTPUT_DIR = _ANIM_DIR / "_output"


def output_path(filename: str) -> str:
    """Absolute path for *filename* inside the gitignored ``_output/`` scratch dir."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    return str(OUTPUT_DIR / filename)


__all__ = ["OUTPUT_DIR", "get_nucleon_coordinates", "output_path"]
