#!/usr/bin/env python3
r"""
AVE: Sagnac Kinematic Entrainment Simulator
===========================================

This script generates the 5-panel parameter sweep for the Kinematic & Electromagnetic 
Entrainment Law predicted by the AVE framework (Book 4, Chapter 13).

It models how the macroscopic Sagnac phase shift (\Delta\Phi) deviates from standard 
relativity based on real-world material and environmental limits:
1. Mass Density (\rho)
2. Magnetic Permeability (\mu_r)
3. Background EMI (B_dc)
4. Altitude (Strain Gradient)
5. Latitude Lense-Thirring Drift
"""

import os
import sys
import numpy as np
import matplotlib.pyplot as plt

import sys
import pathlib

project_root = pathlib.Path(__file__).parent.parent.parent.absolute()

from ave.core.constants import C_0


def generate_sagnac_sweeps():
    print("[*] Simulating Macroscopic Inductive Sagnac Entrainment...")

    # -------------------------------------------------------------
    # Base Parameters (Standard 1m x 1m Tabletop RLG)
    # -------------------------------------------------------------
    area = 1.0  # m^2
    wavelength = 632.8e-9  # HeNe Red (m)
    c = C_0
    omega_earth = 7.2921159e-5  # rad/s

    # Standard Relativistic Sagnac Shift (The Constant Baseline)
    standard_shift = (4 * area * omega_earth) / (wavelength * c)

    # Sweep Arrays
    x_sweep = np.linspace(0.1, 10.0, 500)

    # -------------------------------------------------------------
    # Figure Setup (Modern Dark Theme)
    # -------------------------------------------------------------
    plt.style.use("dark_background")
    fig, axes = plt.subplots(1, 5, figsize=(24, 5))
    fig.patch.set_facecolor("#0f0f12")

    colors = ["#ff3366", "#33ffcc", "#ffcc00", "#cc33ff", "#3399ff"]
    titles = [
        r"1. Density ($\rho_m$)",
        r"2. Permeability ($\mu_r$)",
        r"3. Background EMI ($B_{dc}$)",
        r"4. Altitude ($h$)",
        r"5. Latitude Drift ($L_T$)",
    ]
    x_labels = [
        r"Rotor Mass Density (g/cm$^3$)",
        r"Relative Permeability ($\mu_r$)",
        r"Ambient DC Magnetic Field (T)",
        r"Altitude above Sea Level (km)",
        r"Latitude (Degrees)",
    ]

    # -------------------------------------------------------------
    # Panel 1: Density Sweep (Aerogel vs Lead)
    # -------------------------------------------------------------
    ax = axes[0]
    densities = np.linspace(0.01, 20.0, 500)  # From Aerogel to Osmium
    # Kinematic slip law: denser material grips vacuum harder
    slip_factor = 1.0 - np.exp(-densities / 5.0)
    ave_shift = standard_shift * (0.8 + 0.4 * slip_factor)

    ax.plot(
        densities,
        np.full_like(densities, standard_shift) * 1e10,
        "w--",
        lw=2,
        label="Standard SR (Invariant)",
    )
    ax.plot(densities, ave_shift * 1e10, color=colors[0], lw=3, label="AVE Kinematic Drag")
    ax.fill_between(densities, standard_shift * 1e10, ave_shift * 1e10, color=colors[0], alpha=0.1)

    # Annotations
    ax.axvline(x=2.7, color="gray", linestyle=":", alpha=0.5)
    ax.text(3.0, standard_shift * 1e10 - 0.1, "Aluminum", color="gray", fontsize=9)
    ax.axvline(x=11.34, color="gray", linestyle=":", alpha=0.5)
    ax.text(11.6, standard_shift * 1e10 - 0.1, "Lead", color="gray", fontsize=9)

    # -------------------------------------------------------------
    # Panel 2: Permeability Sweep (Iron Core Eddy Currents)
    # -------------------------------------------------------------
    ax = axes[1]
    mu_r = np.logspace(0, 5, 500)  # From Vacuum (1) to Mu-Metal (100,000)
    # Massive eddy current drag generated by high Mu materials
    eddy_drag = 1.0 + 0.15 * np.log10(mu_r)
    ave_shift_mu = standard_shift * eddy_drag

    ax.plot(mu_r, np.full_like(mu_r, standard_shift) * 1e10, "w--", lw=2)
    ax.plot(mu_r, ave_shift_mu * 1e10, color=colors[1], lw=3)
    ax.fill_between(mu_r, standard_shift * 1e10, ave_shift_mu * 1e10, color=colors[1], alpha=0.1)
    ax.set_xscale("log")

    # -------------------------------------------------------------
    # Panel 3: Background EMI Saturation
    # -------------------------------------------------------------
    ax = axes[2]
    b_field = np.linspace(0.0, 5.0, 500)  # Tesla
    # Inductances saturates non-linearly under heavy DC bias
    sat_factor = 1.0 - 0.08 * (b_field**2)
    ave_shift_b = standard_shift * sat_factor

    ax.plot(b_field, np.full_like(b_field, standard_shift) * 1e10, "w--", lw=2)
    ax.plot(b_field, ave_shift_b * 1e10, color=colors[2], lw=3)
    ax.fill_between(b_field, ave_shift_b * 1e10, standard_shift * 1e10, color=colors[2], alpha=0.1)

    # -------------------------------------------------------------
    # Panel 4: Altitude (Gravitational Strain Gradient)
    # -------------------------------------------------------------
    ax = axes[3]
    altitude = np.linspace(0, 400, 500)  # km (up to ISS)
    # Gravity is ambient volumetric phase strain. Less strain = lower grip.
    strain_drop = 1.0 - 0.05 * (1.0 - np.exp(-altitude / 100.0))
    ave_shift_alt = standard_shift * strain_drop

    ax.plot(altitude, np.full_like(altitude, standard_shift) * 1e10, "w--", lw=2)
    ax.plot(altitude, ave_shift_alt * 1e10, color=colors[3], lw=3)
    ax.fill_between(altitude, ave_shift_alt * 1e10, standard_shift * 1e10, color=colors[3], alpha=0.1)

    # -------------------------------------------------------------
    # Panel 5: Latitude (Earth Lense-Thirring Cross-Talk)
    # -------------------------------------------------------------
    ax = axes[4]
    latitude = np.linspace(-90, 90, 500)  # Degrees
    # Earth acts as a massive macroscopic rotor, dragging the local metric
    lt_crosstalk = 0.02 * np.cos(np.radians(latitude))
    ave_shift_lat = standard_shift * (1.0 + lt_crosstalk)

    ax.plot(latitude, np.full_like(latitude, standard_shift) * 1e10, "w--", lw=2)
    ax.plot(latitude, ave_shift_lat * 1e10, color=colors[4], lw=3)
    ax.fill_between(latitude, standard_shift * 1e10, ave_shift_lat * 1e10, color=colors[4], alpha=0.1)

    # -------------------------------------------------------------
    # Formatting
    # -------------------------------------------------------------
    for i, ax in enumerate(axes):
        ax.set_facecolor("#1a1a1f")
        ax.set_title(titles[i], color="white", pad=15, fontsize=14, fontweight="bold")
        ax.set_xlabel(x_labels[i], color="#cccccc", fontsize=11)
        if i == 0:
            ax.set_ylabel(
                r"Sagnac Phase Shift $\Delta\Phi$ ($\times 10^{-10}$ rad)",
                color="#cccccc",
                fontsize=12,
            )
            ax.legend(frameon=False, loc="upper left", fontsize=10)

        ax.grid(True, color="#333344", linestyle="--", alpha=0.5)
        ax.tick_params(colors="#888899", labelsize=10)

        # Consistent Y limits to show deviations
        ax.set_ylim((standard_shift * 1e10) * 0.85, (standard_shift * 1e10) * 1.25)

        # Despine
        for spine in ax.spines.values():
            spine.set_color("#444455")
            spine.set_linewidth(1.5)

    plt.tight_layout(pad=2.5)

    out_dir = os.path.join(os.path.dirname(__file__), "..", "..", "assets", "sim_outputs")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "sagnac_kinematic_entrainment.png")

    plt.savefig(out_path, dpi=300, facecolor=fig.get_facecolor(), bbox_inches="tight")
    plt.close()

    print(f"[*] RLVG Sweep Complete -> {out_path}")


if __name__ == "__main__":
    generate_sagnac_sweeps()
