"""
Topological Geometry Tensors Module for the AVE Framework.
Analytically computes the rigid 3D bounds and fractional projections of Borromean linkages.
"""

import numpy as np

from ave.core.constants import ALPHA, C_0, ISOTROPIC_PROJECTION


def get_isotropic_strain_projection() -> float:
    """
    Returns the strict geometric bound for how a localized 1D string
    (flux tube tension) projects into a 3D volumetric strain field.

    In the AVE framework, the 6^3_2 Borromean Linkage bounds the total
    topological crossing tensor trace to an exact scalar divisor of 7.
    """
    return ISOTROPIC_PROJECTION


def calculate_topological_nuclear_tension(mass_proton: float, mass_electron: float, lattice_pitch: float) -> float:
    """
    Computes the Mass-Stiffened Strong Force Nuclear Tension.
    Axiom 1: Fundamentally, T_EM = m_e * c^2 / l_node.
    In a Borromean linkage, the baseline inductive inertia of the node
    amplifies the string tension strictly by the (m_p / m_e) ratio.
    """
    # Baseline 1D Electromagnetic String Tension
    T_em = (mass_electron * C_0**2) / lattice_pitch

    # Topological mass stiffening factor
    stiffening_ratio = mass_proton / mass_electron

    # Effective nuclear bonding tension
    T_nuc = T_em * stiffening_ratio
    return T_nuc


def compute_toroidal_halo_volume() -> float:
    """
    Returns the dual-reactance count (= 2) used in the baryon mass eigenvalue.

    SCOPE NOTE (2026-06-01, Grant-adjudicated V=2 reactance-count reframe):
    This function RETURNS A LITERAL constant (2.0); it does NOT perform an
    integration.  The legacy name "toroidal halo volume" is a misnomer and the
    legacy docstring's claim that "the total integration analytically converges
    to exactly 2.0 perfectly" was an overclaim — no integration is performed
    here, and the underlying signed crossing integral
    "V = ∫∫∫ sgn(det) = 2" is itself false (a signed great-circle intersection
    integral vanishes by antisymmetry, evaluating to 0, not 2).

    The "2" is the COUNT of the node's two reactance sectors (Axiom 1:
    3 translational-E DOF → capacitive X_C; 3 microrotational-B DOF → inductive
    X_L), each one electron-ground-state unit feeding the proton's regenerative
    self-consistent mass loop.  It is a dimensionless integer count, not a
    geometric volume; a channel count is counted, not integrated.

    The value 2.0 is correct (mass-confirmed: V=2 → 1836.117 m_e vs CODATA
    1836.153) — only its meaning and the fabricated volume-derivation change.
    Canonical: research/2026-06-01_baryon-V2-dual-reactance-closure.md (§1–§3)
    + manuscript/ave-kb/common/dual-reactance-storage-taxonomy.md.
    """
    # Dual-reactance count: 1 capacitive sector (X_C, translational-E) +
    # 1 inductive sector (X_L, microrotational-B) = 2.  NOT an integration.
    DUAL_REACTANCE_COUNT = 2.0
    return DUAL_REACTANCE_COUNT


def calculate_structural_baryon_eigenvalue() -> float:
    """
    Calculates the exact m_p / m_e structural core eigenvalue.
    Uses the analytical 1D scalar rest-mass contribution (~1162 m_e) plus the
    self-consistent regenerative dual-reactance feedback loop (Black's
    closed-loop form 1/(1 - V*p_c); V = dual-reactance count = 2).
    Reframe 2026-06-01: V is the reactance-sector count, NOT a geometric tensor
    volume — see research/2026-06-01_baryon-V2-dual-reactance-closure.md.
    """
    # 1D Baseline from Faddeev-Skyrme scalar solver (dynamic computation)
    from ave.core.constants import I_SCALAR_1D

    I_scalar = I_SCALAR_1D

    # Dual-reactance count (X_C + X_L sectors); per-channel coupling p_c = 8πα
    V_count = compute_toroidal_halo_volume()
    per_channel_coupling = 8 * np.pi * ALPHA  # p_c (per-channel reactance gain)

    # Regenerative-loop (Black's) form: x_core = I_scalar + (V*p_c)*x_core
    #   => x_core * (1 - V*p_c) = I_scalar  =>  x_core = I_scalar/(1 - V*p_c)
    x_core = I_scalar / (1.0 - (V_count * per_channel_coupling))

    # Add +1 integer topological index loop mandated for global charge constraints
    x_total = x_core + 1.0

    return x_total


def witten_effect_fractionalization() -> list[float]:
    """
    Calculates the exact fractional electric charges generated by the three-fold
    degenerate Z_3 permutation symmetry of the Borromean linkage.
    q_eff = n + (theta / 2pi) e
    """
    # The non-linear dielectric substrate generates three fundamental CP-violating theta angles
    theta_angles = [0, (2 * np.pi) / 3, (4 * np.pi) / 3]

    fractional_charges = []
    for theta in theta_angles:
        # Ground state (n = 0) fractional bounds
        q = 0 + (theta / (2 * np.pi))
        fractional_charges.append(round(q, 3))

    return fractional_charges
